### ISSUE TITLE
release commenting

### ISSUE THREAD

**Issue by mcansh** [mcansh/remix-fastify#85]
```yaml
jobs:
  comment:
    name: 📝 Comment on issues and pull requests
    if: github.repository == 'mcansh/remix-fastify'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📝 Comment on issues
        uses: mcansh/release-comment-action@v0.1.3
        env:
          DIRECTORY_TO_CHECK: "./packages"
          PACKAGE_VERSION_TO_FOLLOW: "@mcansh/remix-fastify"
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
```
